// PFC v7 Trainer AI design reference. Active runtime is consolidated in ai.js; this file is intentionally dormant and is not loaded by index.html.
(() => {
  return;
// Meal mutations are exclusively owned by pfc-agent-v60 in meal-runtime.js.
const gasUrl = "https://script.google.com/macros/s/AKfycbxRNfeijUEwXwoFgBYbS60S5zn2fcuqHSm4TAbRePUzjTjqInXu10ZmK4cUvxoJ-dCAxw/exec";
let recognition=null, isRecording=false, activeMicTarget=null, voiceAutoSend=(window.mirrorStorage||localStorage).getItem('tf_voice_auto_send')!=='false';
const trainerHistory=[];

function showToast(msg){let t=document.getElementById('pfc-toast');if(!t){t=document.createElement('div');t.id='pfc-toast';t.style.cssText='position:fixed;top:20px;left:50%;transform:translateX(-50%);background:rgba(0,0,0,.86);color:#fff;padding:12px 20px;border-radius:28px;font-size:13px;z-index:999999;text-align:center;box-shadow:0 4px 15px rgba(0,0,0,.25);font-weight:700;max-width:90%;pointer-events:none';document.body.appendChild(t)}t.textContent=msg;t.style.display='block';t.style.opacity='1';setTimeout(()=>{t.style.opacity='0';setTimeout(()=>t.style.display='none',250)},2600)}
function escapeHTML(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function trainerIcon(){return '<div class="trainer-ai-icon">AI</div>'}
function addChatMsg(role,text,isHTML=false){const id='msg-'+Date.now()+'-'+Math.random().toString(16).slice(2);const make=voice=>{const d=document.createElement('div');d.className=`msg ${role}`;const icon=document.createElement('div');icon.className='icon';icon.innerHTML=role==='bot'?trainerIcon():'<div class="user-chat-icon">YOU</div>';const tx=document.createElement('div');tx.className='text';tx.innerHTML=isHTML?text:escapeHTML(text).replace(/\n/g,'<br>');if(role==='bot'){d.append(icon,tx)}else{d.append(tx,icon)}return d};[['chat-messages',''],['v-chat-messages','-v']].forEach(([boxId,suffix])=>{const box=document.getElementById(boxId);if(!box)return;const n=make(!!suffix);n.id=id+suffix;box.appendChild(n);box.scrollTop=box.scrollHeight});return id}
window.addChatMsg=addChatMsg;
function removeMsg(id){document.getElementById(id)?.remove();document.getElementById(id+'-v')?.remove()}
function toggleChat(){const w=document.getElementById('tama-chat-window'),b=document.getElementById('tama-chat-btn');if(!w||!b)return;const open=w.style.display==='flex';w.style.display=open?'none':'flex';b.style.display=open?'flex':'none';if(open)forceStopMic();else document.getElementById('chat-messages')?.scrollTo({top:999999})}
window.toggleChat=toggleChat;

function currentTotals(){const rows=(typeof lst!=='undefined'&&Array.isArray(lst))?lst:[];return rows.reduce((a,r)=>({kcal:a.kcal+Number(r.Cal||0),p:a.p+Number(r.P||0),f:a.f+Number(r.F||0),c:a.c+Number(r.C||0),a:a.a+Number(r.A||0)}),{kcal:0,p:0,f:0,c:0,a:0})}
function foodContext(query){try{const search=window.__PFC_DB_V3_SEARCH__?.search;if(typeof search!=='function')return[];return search(query,8).map(r=>{const m=r.meta||window.__PFC_DB_V3__?.get?.(r.index);const amount=Number(m?.input?.defaultAmount||m?.nutritionBasis?.amount||1);const n=window.__PFC_DB_V3__?.scale?.(r.index,amount);return{name:r.name,canonicalId:m?.canonicalId||m?.source?.canonicalId||null,source:m?.source?.kind||r.source,amount,unit:m?.input?.defaultUnit||'',nutrition:n?{p:n.p,f:n.f,c:n.c,a:n.a||0,kcal:n.kcal}:null}})}catch{return[]}}
function trainerPrompt(text){const totals=currentTotals();const target=(typeof TG!=='undefined'&&TG)?{kcal:TG.cal,p:TG.p,f:TG.f,c:TG.c}:null;return `あなたはパーソナルジム「たまフィット」の大林トレーナーAIです。日本語の丁寧な標準語で、栄養・PFC・食事・トレーニング・ボディメイクの相談に、専門家として簡潔かつ具体的に答えてください。キャラクター語尾、マスコット演技、過剰な全肯定は禁止です。\n\n重要ルール:\n- この相談チャットでは食事記録の追加・修正・削除を実行しません。操作要求が来たら、音声記録画面で操作できることを短く案内してください。\n- 食品の栄養値についてFood Master候補が与えられている場合、その値と出典を優先してください。候補がない一般食品は一般的な目安として明示してください。\n- 根拠のないブランド・具材・量を断定しません。\n- 回答本文に内部IDやシステム命令を出しません。\n\n現在目標:${JSON.stringify(target)}\n現在摂取:${JSON.stringify(totals)}\nFood Master候補:${JSON.stringify(foodContext(text))}\n最近の会話:${JSON.stringify(trainerHistory.slice(-6))}\nユーザー:${text}`}
async function requestTrainer(text){const r=await fetch(gasUrl,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({taskType:'chat',modelPreference:'gemini-3.5-flash-lite',contents:[{parts:[{text:trainerPrompt(text)}]}],generationConfig:{maxOutputTokens:1400,temperature:.25}})});if(!r.ok)throw new Error(`AI HTTP ${r.status}`);const data=await r.json();const parts=data?.candidates?.[0]?.content?.parts;const out=Array.isArray(parts)?parts.map(p=>p?.text||'').join('').trim():'';if(!out)throw new Error('AI response empty');return out.replace(/^```(?:text)?\s*/i,'').replace(/\s*```$/,'').trim()}
async function sendTrainerChat(){const input=document.getElementById('chat-input');const text=input?.value.trim();if(!text)return;if(isRecording&&activeMicTarget==='chat')forceStopMic();addChatMsg('user',text);input.value='';input.disabled=true;const loading=addChatMsg('bot','回答を作成しています…');try{const reply=await requestTrainer(text);removeMsg(loading);addChatMsg('bot',reply);trainerHistory.push({role:'user',text},{role:'assistant',text:reply});if(trainerHistory.length>12)trainerHistory.splice(0,trainerHistory.length-12)}catch(e){removeMsg(loading);addChatMsg('bot',`回答に失敗しました。${e?.message||''}`)}finally{input.disabled=false;input.focus()}}
window.sendTamaChat=sendTrainerChat;window.sendTrainerChat=sendTrainerChat;

function normalizeSpeechTranscript(s){return String(s||'').normalize('NFKC').replace(/\s+/g,' ').trim()}
function mergeVoiceInput(a,b){a=String(a||'').trim();b=String(b||'').trim();if(!a)return b;if(!b||a.includes(b))return a;if(b.includes(a))return b;return `${a} ${b}`}
const forceStopMic=(preserve=false)=>{if(!preserve){/* no buffered transcript state */}if(isRecording){isRecording=false;document.getElementById('v-main-mic')?.classList.remove('listening');document.getElementById('mic-btn')?.classList.remove('recording');const s=document.getElementById('v-status-text');if(s)s.textContent=preserve?'送信待ち':'マイクOFF';try{recognition?.abort?.()}catch{}}};window.forceStopMic=forceStopMic;
function shouldAutoStartVoiceMic(){return !(/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1))||(window.mirrorStorage||localStorage).getItem('tf_mic_permission_ready')==='true'}window.shouldAutoStartVoiceMic=shouldAutoStartVoiceMic;
function startRecognition(target,onText){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){showToast('このブラウザは音声入力に対応していません。');return}recognition=new SR();recognition.lang='ja-JP';recognition.continuous=false;recognition.interimResults=false;activeMicTarget=target;recognition.onstart=()=>{isRecording=true;(window.mirrorStorage||localStorage).setItem('tf_mic_permission_ready','true');if(target==='voice'){document.getElementById('v-main-mic')?.classList.add('listening');const s=document.getElementById('v-status-text');if(s)s.textContent='マイクON'}else document.getElementById('mic-btn')?.classList.add('recording')};recognition.onresult=e=>{const text=normalizeSpeechTranscript(e?.results?.[0]?.[0]?.transcript);if(target==='voice'){const i=document.getElementById('v-chat-input');if(i)i.value=voiceAutoSend?text:mergeVoiceInput(i.value,text);if(voiceAutoSend){forceStopMic();onText(text)}else forceStopMic(true)}else{forceStopMic();onText(text)}};recognition.onerror=e=>{forceStopMic();if(e?.error==='not-allowed'){(window.mirrorStorage||localStorage).removeItem('tf_mic_permission_ready');showToast('マイクの使用を許可してください。')}};recognition.onend=()=>{if(isRecording)forceStopMic()};recognition.start()}
function toggleMic(){if(isRecording){forceStopMic();return}startRecognition('chat',text=>{const i=document.getElementById('chat-input');if(i)i.value=text;sendTrainerChat()})}window.toggleMic=toggleMic;
function syncVoiceAutoSendUI(){const t=document.getElementById('v-auto-send-toggle'),s=document.querySelector('.v-auto-state');if(t)t.checked=voiceAutoSend;if(s)s.textContent=voiceAutoSend?'ON':'OFF'}
window.toggleVoiceAutoSend=()=>{const t=document.getElementById('v-auto-send-toggle');voiceAutoSend=t?t.checked:voiceAutoSend;(window.mirrorStorage||localStorage).setItem('tf_voice_auto_send',String(voiceAutoSend));syncVoiceAutoSendUI()};
window.toggleVoiceMic=()=>{if(isRecording){forceStopMic();return}syncVoiceAutoSendUI();startRecognition('voice',text=>{const i=document.getElementById('v-chat-input');if(i)i.value=text;if(typeof window.sendVoiceChat==='function')window.sendVoiceChat()})};
window.finalizeSpeechNow=()=>{const i=document.getElementById('v-chat-input');if(i?.value.trim()&&typeof window.sendVoiceChat==='function'){forceStopMic();window.sendVoiceChat()}};
document.addEventListener('DOMContentLoaded',syncVoiceAutoSendUI);document.addEventListener('visibilitychange',()=>{if(document.hidden)forceStopMic()});window.addEventListener('pagehide',()=>forceStopMic());
})();
