import { readState, writeRecords, writeHistory, writeTargets, writeBody, writeVoiceMode, archiveIfDayChanged, exportBackup, importBackupText, autoMeal } from './storage.js';
import { FOODS, searchFoods, defaultAmount, amountChoices, catalogInfo } from './nutrition/catalog.js';
import { buildRecord, recalcRecord, totals, formatAmount, scaleFood } from './nutrition/engine.js';
import { parseMealTurn, optimisticDraft, trainerReply, AI_INFO } from './ai/client.js';
import { VoiceInput, speak } from './voice/input.js';

const VERSION='CLEAN 1.0';
const state=readState();
archiveIfDayChanged(state);
const ui={view:'home', voiceOpen:false, manualOpen:false, manualFood:null, memo:[], question:'', transcript:'', interim:'', aiBusy:false, voiceState:'idle', editId:null};
let undo=null, toastTimer=null, aiSeq=0;

const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n1=n=>Math.round((Number(n)||0)*10)/10;
const pct=(v,max)=>Math.max(0,Math.min(100,Math.round((Number(v)||0)/(Number(max)||1)*100)));
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function save(){writeRecords(state.records);writeHistory(state.history);writeTargets(state.targets);writeBody(state.body)}
function nameOnly(r){return String(r.N||'').replace(/\([^)]*\)\s*$/,'').replace(/^🤖\s*/,'').trim()}
function amountText(r){if(r?._clean?.amount!=null)return formatAmount(r._clean.amount,r._clean.unit);const m=String(r.N||'').match(/\(([^)]*)\)\s*$/);return m?.[1]||r.U||''}
function summary(){return totals(state.records)}

function homeHtml(){const t=summary(),g=state.targets;const rem=Math.round(g.cal-t.kcal);return `<div class="section-title"><h1>今日の食事バランス</h1><p>カロリーとPFCを見ながら、無理なく続けます。</p></div>
<div class="cal-card"><div class="cal-main"><div><span>今日の摂取</span><strong><b>${Math.round(t.kcal)}</b> kcal</strong><div class="target-note">目標 ${Math.round(g.cal)} kcal</div></div><div class="right"><span>残り</span><strong>${rem>=0?'あと ':''}<b>${Math.abs(rem)}</b> kcal</strong><div class="target-note">${rem>=0?'まだ食べられます':'目標を超えています'}</div></div></div><div class="progress"><i style="width:${pct(t.kcal,g.cal)}%"></i></div></div>
<div class="macro-grid">${macro('p','P','たんぱく質',t.p,g.p,'身体をつくる材料')}${macro('f','F','脂質',t.f,g.f,'ホルモン・細胞に必要')}${macro('c','C','炭水化物',t.c,g.c,'活動の主なエネルギー')}</div>
<div class="primary-actions"><button class="voice-main" data-action="voice"><div class="mic">MIC</div><div><strong>話して記録</strong><small>食べたものをそのまま話してください</small></div></button><button class="manual-main" data-action="manual"><strong>手で入力</strong><small>食品を検索</small></button></div>
<div class="records-section"><div class="section-head"><h2>今日の記録</h2><span>${state.records.length}件</span></div>${recordsHtml()}</div>
<div class="trainer-card"><div class="section-head"><h2>トレーナーAI</h2><span>記録は変更しません</span></div><div class="trainer-log" id="trainer-log"><div class="chat-line bot">食事やトレーニングについて質問できます。</div></div><form class="chat-compose" id="trainer-form"><input id="trainer-input" placeholder="例：今日のPFCどう？"><button>送信</button></form></div>`}
function macro(k,l,name,val,goal,note){return `<div class="macro-card ${k}"><div><b>${l}</b><span>${name}</span></div><strong>${n1(val)} / ${n1(goal)}g</strong><small>${note}<br>残り ${n1(Math.max(0,goal-val))}g</small><div class="progress"><i style="width:${pct(val,goal)}%"></i></div></div>`}
function recordsHtml(){if(!state.records.length)return `<div class="empty-card">まだ記録がありません。<br>「話して記録」から始められます。</div>`;return [...state.records].reverse().map(r=>`<div class="record-card" data-id="${r.id}"><div class="record-main"><div><strong>${esc(nameOnly(r))}</strong><span>${esc(r.time||'')}・${esc(amountText(r))}</span></div><b>${Math.round(r.Cal||0)} kcal</b></div><div class="record-macros">P ${n1(r.P)}g　F ${n1(r.F)}g　C ${n1(r.C)}g${Number(r.A)>0?`　A ${n1(r.A)}g`:''}</div><div class="record-actions"><button class="ghost-btn" data-action="edit-record" data-id="${r.id}">直す</button><button class="ghost-btn danger" data-action="delete-record" data-id="${r.id}">削除</button></div></div>`).join('')}
function historyHtml(){const current={d:'今日',s:summary(),l:state.records};const all=[current,...state.history];return `<div class="section-title"><h1>履歴</h1><p>過去の食事を見返せます。</p></div>${all.map((h,i)=>`<div class="history-day ${i===0?'current':''}"><div class="history-head"><strong>${esc(h.d)}</strong><span>${Math.round(h.s?.Cal??h.s?.kcal??0)} kcal</span></div><div>P ${n1(h.s?.P??h.s?.p)}g　F ${n1(h.s?.F??h.s?.f)}g　C ${n1(h.s?.C??h.s?.c)}g</div><details><summary>${h.l?.length||0}件の記録</summary><div class="history-items">${(h.l||[]).map(x=>`<div><span>${esc(nameOnly(x))}</span><b>${Math.round(x.Cal||0)} kcal</b></div>`).join('')}</div></details></div>`).join('')}`}
function bodyHtml(){return `<div class="section-title"><h1>からだ</h1><p>体重などをシンプルに残します。</p></div><form id="body-form" class="panel body-form"><label>体重 kg<input id="body-weight" inputmode="decimal" required></label><label>体脂肪 %<input id="body-fat" inputmode="decimal"></label><button class="primary-btn" type="submit">今日の記録を追加</button></form><div>${[...state.body].reverse().slice(0,60).map(x=>`<div class="body-row"><b>${esc(x.date||x.d||'')}</b><span>${x.weight??x.w??'-'} kg</span><span>${x.fat??x.bf??'-'} %</span><span></span></div>`).join('')}</div>`}
function settingsHtml(){const g=state.targets, info=catalogInfo();return `<div class="section-title"><h1>設定</h1><p>目標とデータを管理します。</p></div><form id="target-form" class="panel settings-grid"><label>目標 kcal<input id="set-cal" inputmode="numeric" value="${g.cal}"></label><label>P g<input id="set-p" inputmode="decimal" value="${g.p}"></label><label>F g<input id="set-f" inputmode="decimal" value="${g.f}"></label><label>C g<input id="set-c" inputmode="decimal" value="${g.c}"></label><button class="primary-btn" type="submit">目標を保存</button></form><div class="panel backup-panel"><h2>バックアップ</h2><p>ユーザーデータは従来と同じlocalStorageキーを使っています。</p><div class="button-row"><button class="secondary-btn" data-action="export">書き出す</button><label class="secondary-btn">読み込む<input id="import-file" type="file" accept="application/json" hidden></label></div></div><div class="panel runtime-panel"><h2>Clean Runtime</h2><p>${VERSION}<br>Food Master ${info.foods}食品（base ${info.baseRows} / MEXT ${info.mextRows}）<br>AI ${AI_INFO.model}<br>Service Worker: 使用しない<br>旧V35/V42 runtime: 読み込まない</p></div>`}
function render(){for(const v of ['home','history','body','settings']){$(`#view-${v}`).hidden=ui.view!==v;$('.nav-btn[data-view="'+v+'"]').classList.toggle('active',ui.view===v)}if(ui.view==='home')$('#view-home').innerHTML=homeHtml();if(ui.view==='history')$('#view-history').innerHTML=historyHtml();if(ui.view==='body')$('#view-body').innerHTML=bodyHtml();if(ui.view==='settings')$('#view-settings').innerHTML=settingsHtml();if(ui.voiceOpen)renderVoice();if(ui.manualOpen)renderManual()}

function openVoice(){ui.voiceOpen=true;ui.memo=[];ui.question='';ui.transcript='';ui.interim='';$('#voice-modal').hidden=false;renderVoice()}
function closeVoice(){voice.stop();ui.voiceOpen=false;$('#voice-modal').hidden=true;render()}
function modeLabel(m){return m==='voice'?['音声入力','食べたものを話して記録']:m==='chat'?['会話','必要な時だけAIが聞き返す']:['おまかせ','必要な時だけ自動で会話']}
function memoReady(){return ui.memo.length>0&&ui.memo.every(x=>x.foodId&&!x.unresolved&&!x.needsAmount&&Number(x.amount)>0)}
function renderVoice(){const sheet=$('#voice-sheet');if(!sheet)return;const modes=['voice','chat','auto'];sheet.innerHTML=`<div class="modal-head"><div><strong>話して記録</strong><small>AIが横で食事メモを取ります</small></div><button class="close-btn" data-action="close-voice">×</button></div><div class="mode-tabs">${modes.map(m=>{const [a,b]=modeLabel(m);return `<button class="voice-mode ${state.voiceMode===m?'selected':''}" data-mode="${m}"><b>${a}</b><small>${b}</small></button>`}).join('')}</div><div class="listen-card"><div class="voice-status">${voiceStatus()}</div><button class="mic-button ${ui.voiceState==='listening'?'listening':''}" data-action="toggle-mic"><span></span>${ui.voiceState==='listening'?'聞いています':'マイクを押す'}</button><div class="transcript">${esc(ui.transcript||ui.interim||'食べたものを話してください。例：鶏むね150gと白米200g、納豆')}</div></div><div class="voice-question">${esc(ui.question)}</div><div class="memo-card"><div class="memo-title"><strong>今日の食事メモ</strong><small>${ui.aiBusy?'AIが整理中…':'確認してまとめて登録'}</small></div>${memoHtml()}</div><div class="voice-text-fallback"><label>文字でも追加・修正できます<input id="voice-text" placeholder="例：鶏むね150g、納豆、味噌汁"></label></div><div class="voice-footer"><button class="primary-btn" data-action="register-memo" ${memoReady()?'':'disabled'}>これで登録する</button><button class="secondary-btn" data-action="voice-fix">修正する</button></div>`}
function voiceStatus(){if(ui.aiBusy)return '内容を整理しています…';if(ui.voiceState==='listening')return '聞いています。ゆっくり話して大丈夫です';if(ui.voiceState==='reconnecting')return 'そのまま続けてください';return 'マイクを押して話してください'}
function memoHtml(){if(!ui.memo.length)return `<div class="memo-empty">食品名を聞き取ったら、ここへすぐ追加します。</div>`;return ui.memo.map(x=>`<div class="memo-row ${x.needsAmount||x.unresolved?'needs':''}"><div><strong>${esc(x.name)}</strong><span>${x.unresolved?'食品を確認':x.needsAmount?'量を確認中':`${esc(formatAmount(x.amount,x.unit))}${x.assumed?'（仮）':''}`}</span></div><button class="memo-remove" data-action="memo-remove" data-key="${esc(x.key)}">×</button></div>`).join('')}
async function processSpeech(text){const clean=String(text||'').trim();if(!clean)return;ui.transcript=clean;ui.interim='';ui.memo=optimisticDraft(clean,ui.memo);ui.aiBusy=true;renderVoice();const seq=++aiSeq;try{const result=await parseMealTurn(clean,ui.memo,state.voiceMode);if(seq!==aiSeq)return;if(result.items.length)ui.memo=result.items;ui.question=result.question||'';if((state.voiceMode==='chat'||state.voiceMode==='auto')&&ui.question){speak(ui.question,()=>{if(ui.voiceOpen)voice.start({clear:true})})}}catch(e){console.warn('[Clean AI]',e);ui.question=ui.memo.some(x=>x.needsAmount)?'量が分からない食品があります。分量を話すか「修正する」から入力してください。':'AIの整理に時間がかかっています。聞き取ったメモは残しています。';toast('メモは残しています')}finally{if(seq===aiSeq){ui.aiBusy=false;renderVoice()}}}
const voice=new VoiceInput({onText:(chunk,full)=>{ui.transcript=full;ui.interim='';renderVoice()},onInterim:(t,full)=>{ui.interim=[full,t].filter(Boolean).join(' ');renderVoice()},onState:s=>{ui.voiceState=s;renderVoice()},onError:e=>{console.warn('[voice]',e);toast(e==='unsupported'?'このブラウザでは音声入力を使えません':'音声入力を再試行してください')}});
function submitVoiceBuffer(){const text=voice.getText()||$('#voice-text')?.value||ui.transcript;if(text){voice.stop();processSpeech(text)}}

function openManual(record=null){ui.manualOpen=true;ui.manualFood=null;ui.editId=record?.id||null;$('#manual-modal').hidden=false;renderManual(record)}
function closeManual(){ui.manualOpen=false;ui.manualFood=null;ui.editId=null;$('#manual-modal').hidden=true}
function renderManual(record=null){const sheet=$('#manual-sheet');if(!sheet)return;let body='';if(ui.manualFood){const f=ui.manualFood,d=defaultAmount(f),choices=amountChoices(f);const existing=ui.editId?state.records.find(r=>Number(r.id)===Number(ui.editId)):null;const amount=existing?existing._clean?.amount||d.amount:d.amount,unit=existing?existing._clean?.unit||d.unit:d.unit;const scaled=scaleFood(f,amount,unit);body=`<div class="manual-form"><h3>${esc(f.name)}</h3><div class="form-row"><label>量<input id="manual-amount" inputmode="decimal" value="${amount}"></label><label>単位<input id="manual-unit" value="${esc(unit)}"></label><label>食事<select id="manual-meal">${['朝','昼','晩','間食'].map(m=>`<option ${m===(existing?.time||autoMeal())?'selected':''}>${m}</option>`).join('')}</select></label></div><div class="choice-row">${choices.map(v=>`<button class="choice-chip" data-amount="${v}">${formatAmount(v,d.unit)}</button>`).join('')}</div><div class="manual-preview">${scaled?`${scaled.kcal} kcal　P${scaled.p} F${scaled.f} C${scaled.c}`:'量を確認してください'}</div><button class="primary-btn wide" data-action="save-manual">${existing?'更新する':'追加する'}</button></div>`}else body=`<input id="food-search" class="search-input" placeholder="食品名を検索"><div class="food-results" id="food-results"><div class="manual-hint">例：白米、鶏むね、納豆、味噌汁</div></div>`;sheet.innerHTML=`<div class="modal-head"><div><strong>${ui.editId?'記録を直す':'手で入力'}</strong><small>Food Masterから登録</small></div><button class="close-btn" data-action="close-manual">×</button></div>${body}`;if(!ui.manualFood&&ui.editId){const r=state.records.find(x=>Number(x.id)===Number(ui.editId));const id=r?._clean?.foodId||r?._dbv3?.id;if(id){ui.manualFood=FOODS.find(f=>f.id===id)||null;if(ui.manualFood)return renderManual()}}}
function searchManual(q){const hits=searchFoods(q,20);$('#food-results').innerHTML=hits.length?hits.map(f=>`<button class="food-hit" data-food-id="${esc(f.id)}"><span><strong>${esc(f.name)}</strong><small>${esc(f.category)}・${esc(f.nutritionBasis.raw)}</small></span><b>${f.source.kind==='mext'?'MEXT':'Food Master'}</b></button>`).join(''):`<div class="manual-hint">見つかりませんでした</div>`}
function registerMemo(){const records=[];for(const item of ui.memo){const r=buildRecord({foodId:item.foodId,amount:item.amount,unit:item.unit,meal:item.meal});if(r)records.push(r)}if(!records.length)return;state.records.push(...records);save();closeVoice();toast(`${records.length}件を登録しました`)}
function deleteRecord(id){const i=state.records.findIndex(x=>Number(x.id)===Number(id));if(i<0)return;undo={item:state.records[i],index:i};state.records.splice(i,1);save();render();toast('削除しました')}
async function retireWorkers(){if(!('serviceWorker'in navigator))return;try{const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.filter(r=>{try{return new URL(r.scope).pathname.startsWith('/pfc-mirror/')}catch{return false}}).map(r=>r.unregister()));}catch(e){console.warn(e)}}

addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){ui.view=nav.dataset.view;render();return}const act=e.target.closest('[data-action]')?.dataset.action;if(act==='voice')openVoice();if(act==='manual')openManual();if(act==='close-voice')closeVoice();if(act==='close-manual')closeManual();if(act==='toggle-mic'){if(voice.active)submitVoiceBuffer();else voice.start({clear:true})}if(act==='register-memo')registerMemo();if(act==='voice-fix'){voice.stop();ui.question='直したいところを話すか、下の入力欄に書いてください。';renderVoice();$('#voice-text')?.focus()}if(act==='memo-remove'){const key=e.target.closest('[data-key]').dataset.key;ui.memo=ui.memo.filter(x=>x.key!==key);renderVoice()}if(act==='delete-record')deleteRecord(e.target.closest('[data-id]').dataset.id);if(act==='edit-record')openManual(state.records.find(x=>Number(x.id)===Number(e.target.closest('[data-id]').dataset.id)));if(act==='save-manual'){const f=ui.manualFood,amount=Number($('#manual-amount').value),unit=$('#manual-unit').value,meal=$('#manual-meal').value;let r;if(ui.editId){const old=state.records.find(x=>Number(x.id)===Number(ui.editId));r=recalcRecord(old,amount,unit)||buildRecord({food:f,amount,unit,meal,id:ui.editId});if(r)r.time=meal;const i=state.records.findIndex(x=>Number(x.id)===Number(ui.editId));if(i>=0&&r)state.records[i]=r}else r=buildRecord({food:f,amount,unit,meal});if(r){if(!ui.editId)state.records.push(r);save();closeManual();render();toast('保存しました')}}if(act==='export'){const blob=new Blob([exportBackup()],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pfc_backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}if(e.target.closest('[data-mode]')){state.voiceMode=e.target.closest('[data-mode]').dataset.mode;writeVoiceMode(state.voiceMode);renderVoice()}if(e.target.closest('[data-food-id]')){ui.manualFood=FOODS.find(f=>f.id===e.target.closest('[data-food-id]').dataset.foodId)||null;renderManual()}if(e.target.closest('[data-amount]')){const input=$('#manual-amount');if(input){input.value=e.target.closest('[data-amount]').dataset.amount;input.dispatchEvent(new Event('input',{bubbles:true}))}}if(e.target.id==='reload-btn')location.reload()});
addEventListener('input',e=>{if(e.target.id==='food-search')searchManual(e.target.value);if(e.target.id==='manual-amount'||e.target.id==='manual-unit'){const f=ui.manualFood,amount=Number($('#manual-amount')?.value),unit=$('#manual-unit')?.value,s=scaleFood(f,amount,unit);const p=$('.manual-preview');if(p)p.textContent=s?`${s.kcal} kcal　P${s.p} F${s.f} C${s.c}`:'量を確認してください'}});
addEventListener('keydown',e=>{if(e.target.id==='voice-text'&&e.key==='Enter'){e.preventDefault();const t=e.target.value.trim();if(t){e.target.value='';processSpeech(t)}}});
addEventListener('submit',async e=>{if(e.target.id==='target-form'){e.preventDefault();state.targets.cal=Number($('#set-cal').value)||2000;state.targets.p=Number($('#set-p').value)||0;state.targets.f=Number($('#set-f').value)||0;state.targets.c=Number($('#set-c').value)||0;save();render();toast('目標を保存しました')}if(e.target.id==='body-form'){e.preventDefault();const w=Number($('#body-weight').value),fat=Number($('#body-fat').value);if(!w)return;state.body.push({date:new Date().toISOString().slice(0,10),weight:w,fat:Number.isFinite(fat)?fat:null,id:Date.now()});save();render();toast('体組成を追加しました')}if(e.target.id==='trainer-form'){e.preventDefault();const input=$('#trainer-input'),text=input.value.trim();if(!text)return;const log=$('#trainer-log');log.insertAdjacentHTML('beforeend',`<div class="chat-line user">${esc(text)}</div><div class="chat-line bot loading">考えています…</div>`);input.value='';try{const reply=await trainerReply(text,{targets:state.targets,totals:summary()});log.lastElementChild.className='chat-line bot';log.lastElementChild.textContent=reply}catch{log.lastElementChild.className='chat-line bot';log.lastElementChild.textContent='今はAIに接続できません。少し時間を置いてください。'}}});
addEventListener('change',e=>{if(e.target.id==='import-file'){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const count=importBackupText(String(reader.result));Object.assign(state,readState());render();toast(`${count}項目を読み込みました`)}catch(err){toast(err.message)}};reader.readAsText(file)}});

await retireWorkers();
render();
console.info('[PFC Clean]',{version:VERSION,foods:catalogInfo(),legacyRuntime:false,serviceWorker:false});
